### ISSUE TITLE
Advanced Omnibox functionality

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/wikipedia-search#12]
From email:

Working in a multilingual environment, I immediately thought that it’d be great to be able to tweak the search language directly during the search in the address bar. Maybe using a shortcut like
wiki <two-letter-language-code> search term
as in
wiki en hamburger
or
wiki it spaghetti
etc.
 
It’s that I do a lot of searches and flipping from one language to another one while already ON the Wikipedia search result page can be a pain… 😝

**Comment by alexis-** [comment]
I was just about to suggest the same enhancement. That would be incredibly useful. Thank you for making wikipedia-search.

**Comment by corbindavenport** [comment]
I'll definitely make this a priority for the next release.

**Comment by corbindavenport** [comment]
In progress :)

![Peek 2019-12-15 22-09](https://user-images.githubusercontent.com/3879063/70876463-aeaf6e00-1f87-11ea-8d38-a2d15d7aab1e.gif)

**Comment by corbindavenport** [comment]
Wikipedia Search v10 is now rolling out with this included.
