### ISSUE TITLE
Searches with special characters don't work

### ISSUE THREAD

**Issue by m-spiegel** [corbindavenport/wikipedia-search#16]
Hi—

I'm no longer able to search for articles containing special characters in the name. For example, when I type "wiki AT&T" into the search bar, it pulls up the page for "AT" and when I type "wiki C++" it pulls up the page for C. I pretty sure this used to work, and it's very frustrating! I'm running Chrome 74.0.3729.169 on macOS 10.14.5.

Thanks!

**Comment by corbindavenport** [comment]
This is now fixed in the `dev` branch:

![Peek 2019-12-22 19-14](https://user-images.githubusercontent.com/3879063/71329159-8972b080-24ef-11ea-86a1-ec528a618577.gif)

**Comment by corbindavenport** [comment]
Wikipedia Search v10 is now rolling out with this included.
