### ISSUE TITLE
Citation ability is gone

### ISSUE THREAD

**Issue by sshah49** [corbindavenport/wikipedia-search#2]
When I am editing a Wikipedia article, and click the citation dropdown>Template, and any citation template, the space where citation info would go is comp blank. Looks like a bug has removed all data.

**Comment by corbindavenport** [comment]
I temporarily uninstalled Wikipedia Search to see if this was a problem with the extension, but it still has that problem with the extension turned off. It appears to be a problem with Wikipedia itself.
