### ISSUE TITLE
Turn off multi-language support?

### ISSUE THREAD

**Issue by m-spiegel** [corbindavenport/wikipedia-search#22]
I really love your extension, but is there any way to turn off multi-language support? I only want to search English Wikipedia, but when I type, e.g. "wiki la law" looking for the 80s TV series, it takes me to the Latin language Wikipedia. Thanks!

**Comment by corbindavenport** [comment]
I'll have to add a setting for that, yeah.

**Comment by corbindavenport** [comment]
Wikipedia Search v10.1 with this option is being reviewed by Google, and should be available soon.
