### ISSUE TITLE
Add Wikipedia mobile search? 

### ISSUE THREAD

**Issue by VanishBlox** [corbindavenport/wikipedia-search#26]
I would like it if there was a setting which would transform the wiki urls into mobile versions after you find them, I find the mobile versions easier to read. 

for example:

https://de.wikipedia.org/wiki/Wikipedia -> https://de.m.wikipedia.org/wiki/Wikipedia

**Comment by corbindavenport** [comment]
That wouldn't be too difficult to add, sure.

**Comment by corbindavenport** [comment]
Finished the code for this, it will go live in the next update:

![image](https://user-images.githubusercontent.com/3879063/120963449-9b6e0080-c72f-11eb-99a9-53d7d70ddbef.png)

**Comment by corbindavenport** [comment]
Wikipedia Search v10.1 with this option is being reviewed by Google, and should be available soon.
