### ISSUE TITLE
Unable to modify *Subject/headline* or *edit summary* fields using Opera v32

### ISSUE THREAD

**Issue by zephalis** [corbindavenport/wikipedia-search#3]
/* Symptoms */
* last character typed remains on preview, but doesn't show in the textbox
* |clear| button works
* The subject dropdown menu functions properly
* <alt+shift> functions don't work
* Not an issue in FF or Chrome

/* Environment Info */
BrowserVersion: 32.0.1948.44
BrowserID: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36 OPR/32.0.1948.44
Windows v10.0.10586 x64

**Comment by corbindavenport** [comment]
Could you clarify what you mean by the last character remains on preview? Also what do you mean by functions?
