### ISSUE TITLE
Is there any way to show the wikipedia pages right away in the suggestions without pressing tab?

### ISSUE THREAD

**Issue by ninesalt** [corbindavenport/wikipedia-search#5]
I'm trying to go through your code to find a way to do this. Does chrome even allow this?

**Comment by corbindavenport** [comment]
As far as I know, Chrome does not support anything different from typing
'wiki' and either pressing tab or space.

**Comment by Swailem95** [comment]
So you can't bypass that step and show the wiki suggestions right away without needing to hit tab/space? I'll try to mess around with it a bit, I'll see what I can do.

**Comment by corbindavenport** [comment]
Closing because I don't think this can be fixed.
