### ISSUE TITLE
Strange omnibox behavior

### ISSUE THREAD

**Issue by corbindavenport** [corbindavenport/wikipedia-search#8]
From email:

Often when using the Wiki Search extension for Chrome this happens, for example:
I type "wiki savannah g".  At this instant, I see "Savannah Guthrie" in plain text in the instant results below the search bar.

But my brain is still commanding me to type, so I hit a couple more keys and I now have typed
"wiki savannah gut".  Now Savannah Guthrie has disappeared from the instant results!  In fact, there are no plain text results.  Everything is in the form of a complete URL, like this:
"https://en.wikipedia.org/wiki/Savannah_Guthrie - Savannah Guthrie - Wikipedia"

If I remove  2 or 3 letters from the end, Savannah Guthrie in plain text shows up again in the instant results.

I am not misspelling her name.  I'm actually getting closer to her complete name, but her plain text name disappears from the instant results.

When it changes from plain text to a URL, it is just harder to read, and I have to make sure it is going to Wikipedia and not somewhere else.  Sometimes these URLs take me to a Google Search page instead of Wikipedia.

This happens all the time with all kinds of searches.  I hope you can fix it!  Thanks!  -Ric

**Comment by fakanal01** [comment]
Thank you post!Welcome fakanal01 caffee.

**Comment by corbindavenport** [comment]
This looks like an issue on Wikipedia's end, I don't think I can fix this.
